### ISSUE TITLE
Why is datapusher url referenced in xloader controller action?

### ISSUE THREAD

**Issue by camfindlay** [davidread/ckanext-xloader#26]
See https://github.com/davidread/ckanext-xloader/blob/master/ckanext/xloader/action.py#L325

I've been testing installing xloader and when I got to view a Datastore tab for a resoruce in the web ui I get a stack trace...

```
File '/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/controllers.py', line 38 in resource_data
  None, {'resource_id': resource_id}
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 457 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckanext-xloader/ckanext/xloader/action.py', line 328 in xloader_status
  {'configuration': ['ckan.datapusher.url not in config file']})
ValidationError: {'configuration': ['ckan.datapusher.url not in config file']}
```
If this module replaced datapusher altogether, why is this config option being referenced because it's causing a regression elsewhere in the application.

Reporting as a bug.

**Comment by davidread** [comment]
@camfindlay many thanks for flagging this up. Apologies, about this straggler. I've now released the fix in version 0.3.1.
