### ISSUE TITLE
Unicode characters in column names break the loader

### ISSUE THREAD

**Issue by metaodi** [davidread/ckanext-xloader#28]
I tried to import a file with unicode characters in the header (in my case they were German umlauts), this leads to some ugly UnicodeDecode errors during the loading, e.g.

```
[ckanext.xloader.jobs] xloader error: 'ascii' codec can't encode character u'\xfc' in position 3: ordinal not in range(128)
```

Initially I could pin this issue down to some log messages that were mixing strings with unicode (e.g. `logger.info('Fields: {}'.format(fields))` which fails if `fields` contains unicode characters. But upon fixing this, I realized that the current implemented of DataStore in CKAN core couldn't handle unicode column names as well. While it might be possible to fix this at some point, I'm not sure if it's generally a good idea to have unicode characters in column names.

I'll submit a PR later, where we could discuss the implementation of my solution.

**Comment by davidread** [comment]
Thanks for spotting this - super to receive a PR!

I agree, we totally need to improve the column name mapping bit of datapusher/xloader. How about we do an discussion on the [ckan ideas page](https://github.com/ckan/ideas-and-roadmap/issues)?

**Comment by camfindlay** [comment]
Good discussion, I also found the XLoader makes all the column names CAPITALS instead of how they are expressed in the source CSV. Was there a reason for that or something we can look at alter so the final json api reads more like how datapusher ingests data?

**Comment by davidread** [comment]
@camfindlay Can you check it does make them capitals? In the tests the column names appear to keep their original case e.g. https://github.com/davidread/ckanext-xloader/blob/master/ckanext/xloader/tests/test_loader.py#L166 has "OnTime_Status". If you're still seeing it, do open a new issue - thanks.
